modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Vazkii/Psi"

[[mods]]
modId="quark"
displayName="Quark"
version="${version}"
authors="Vazkii, Wiiv, WireSegal, MCVinnyq"
description='''
Small things.
'''

[[dependencies.quark]]
    modId="arl"
    mandatory=true
    versionRange="[1.4-34,)"
    ordering="AFTER"
    side="BOTH"
